title: Slava Petrov   # your title
author: Slava Petrov # your name
description: Just have some fun here # your description
avatar: https://secure.gravatar.com/avatar/4fc76de0d6edf025dff76b4b2c5997e8 

# Build Settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"
gems: [jekyll-paginate]

# Comments
# disqus:
#   shortname: xxxx-xxxxx-xxx   # your disqus shortname

# Google Analytics
# google_analytics: xx-xxxxxxxx-1  # your google analytics
